# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
if [ -d ~/.shellrc.d ]; then
    for i in $(find $HOME/.shellrc.d/ -name '*.sh' -o -name '*.zsh' | sort); do
        . $i
    done
    unset i
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# BENTO REMOTE: This block will load up all '*.zsh' files in ~/.zshrc.d/ in alphabetical order into your shell. 
# If you remove this block you will break future updates for your Bento Remote instance

#if [ -d ~/.zshrc.d ]; then
#    for i in $(find $HOME/.zshrc.d/ -name '*.zsh' -o -name '*.sh' | sort); do
#        . $i
#    done
#    unset i
#fi
# --- 

### CUSTOMIZING YOUR BENTO REMOTE

## Shell Customization
# It is highly recommended that you add your zshrc customizations into new individual files in the ~/.zshrc.d 
# directory rather than modifying this file directly.
# For example: You can create a file called `~/.zshrc.d/user.zsh` and it will be sourced into your shells
# This .zshrc file you're looking at right now will be replaced when you get a new Bento Remote instance
# While files in ~/.zshrc.d will be automatically copied over to your new Bento Remote.

## Oh My Zsh
# Oh My Zsh is included by default in the Bento Remote image. If you want to customize it, you must copy the default
# config to a new file named "~/.zshrc.d/oh-my-zsh.zsh" and then customize that file. Note that the filename must
# be exactly "~/.zshrc.d/oh-my-zsh.zsh" in order to override the default config.
# To customize: cp "$HOME/.oh-my-zsh/templates/zshrc.zsh-template" "$HOME/.zshrc.d/oh-my-zsh.zsh"

## Hooks
# Bento can automatically run scripts to preinstall things for you when you create a new Bento Remote
# You can use hooks to further customize the Bento Remote experience for yourself
# See https://go/bento-remote-hooks for details
 
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


### BEGIN--Instacart Shell Settings. (Updated: Thu Jan 18 15:28:51 PST 2024. [Script Version 1.3.27]) NO-TOUCH
# This Line Added Automatically by Instacart Setup Script
# The sourced file contains all of the instacart utilities and shell settings
# To remove this functionality, leave the block, and enter "NO-TOUCH" in the BEGIN line, and comment the line below:
#source /home/bento/.instacart_shell_profile
### END--Instacart Shell Settings.
